---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
# spring config for noun client app only
spring:
  profiles: lab4-noun
words: boat,book,vote,seat,backpack,partition,groundhog  
